spring.application.name=ApachePoiPoc

# Logging Configuration
logging.level.root=INFO
logging.level.com.example.ApachePoiPoc=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/application.log

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Server Configuration
server.port=8080

